### PR TITLE
add immutable Array operators

### PR DESCRIPTION
**Pull request by malash**
Immutable `Array` operators is for less code in `on-` callback arrow functions.
In `dataton` they are `Array.prototype.xfunctions` https://github.com/ssnau/dataton/blob/master/index.js#L394-L409

```jsx
// before
<button
  onClick={() => state.set('todos', (state.get('todos') || []).concat(this.state.inputValue))}
>Add</button>

// or
<button
  onClick={() => {
    const array = state.get('todos') || [];
    // shallow clone
    const newArray = Array.from(array);
    newArray.push(this.state.inputValue);
    state.set('todos', newArray)
  }}
>Add</button>

// after
<button
  onClick={() => state.push('todos', this.state.inputValue)}
>Add</button>
```
Because the operators use `Array.from` to shallow clone the old array, `object`, `string` and other non-array variables will be conveyed to `[]` . (as also as `null` and `undefined`)

There are still 2 problem to resolve.

1. Should `state` support immutable prototype like `concat`, `indexOf` or `map` ?
```js
state.get('array').concat([1, 2, 3]);
// or
state.concat('array', [1,2,3]); // this won't change state
```

2. All `Array` operators must have the first argument `subPath` while `state.get` and `state.set` don't need that may make user confused. What about to make `subPath` required for `get` and `set`?
```js
console.log(state.get(''));
const cursor = state.cursor('a');
cursor.set('', 'value');
```

### CODE REVIEW

**Review by ssnau — CHANGES_REQUESTED** [review]
Your implementation has violated the `copy-on-write` rule. Moreover, calling `push` won't emit event in this way and PureComponent won't be re-rendered based on the fact that the manipulated element doesn't change.

```
state.push('path', value)
// should equals to
var array = state.get('path') || [];
var newArray = state.concat(value);
state.set('path', newArray);
```

please let `noflux` follows the immutable pattern and assign a new value to the cursor instead of mutating it.

**Comment by ssnau** [comment]
some tips about the questions:

1. we don't need to support that as users could always call `state.get().map(x=> ...`. The only reason we implement `push | pop | shift | unshift | remove ` is that we know they are mutating the element and user may not always notice it. Thus, after calling these methods on the element, Component won't re-render.

2. could we also make `subPath` optional and set a restriction for `push | pop` that can only push an element once a time?

**Comment by malash** [comment]
> Your implementation has violated the copy-on-write rule...

@ssnau the `arrayFromAllowNullOrUndefined` function in `utils.js` always create a shallow clone of given array.

https://github.com/nofluxjs/noflux-state/pull/8/files?diff=unified#diff-2b4ca49d4bb0a774c4d4c1672d7aa781R71

**Comment by malash** [comment]
@ssnau About your some tips.

1. I agree with your explanation.

2. The implement now is compact with `Array.prototype` but with an extra argument `subPath` although few people use `push` or `unshift` with multi values. Supporting only one value usage is considerable.

**Comment by ssnau** [comment]
LGTM. Please consider the following tips:

1. make `subPath` optional.

2. add tests to show that we are creating a copy rather than mutating the existing object.

**Review by ssnau — APPROVED** [review]

**Comment by ssnau** [comment]
some proposals:

- remove `subPath` parameter and make sure these methods directly operating the underlying cursor values.

```
var cursor = state.get('person');
cursor.cursor('hobbies').push('football', 'basketball');
```

**Pull request merged**
